### ISSUE TITLE
网站失效

### ISSUE THREAD

**Issue by linlinzzo** [NUAA-Open-Source/BlogRoll#52]
- https://kit4y.github.io/ 出现了404
- https://wuwm.nuaax.com/ DNS_PROBE_FINISHED_NXDOMAIN
- https://blog.wansho.cn/ 出现404
- https://blog.waitforaday.site/ DNS_PROBE_FINISHED_NXDOMAIN
- https://ashinz.cn/ ERR_CONNECTION_REFUSED
- https://alst0n.site/ DNS_PROBE_FINISHED_NXDOMAIN

**Comment by villivateur** [comment]
感谢，已在 [687a451](https://github.com/NUAA-Open-Source/BlogRoll/commit/687a451b6e935f550356021d1a8a133c4c67cc3b) 修正
